### ISSUE TITLE
Collision detection at receiver scaling to 'n' mediums 

### ISSUE THREAD

**Issue by scottmarshall17** [mackncheesiest/ECE478_Projects#3]
We need to create better collision detection schemes at the receivers in order to successfully implement the CSMA/CA with and without virtual carrier sensing and topology B.

**Comment by mackncheesiest** [comment]
The results seem to be promising. Threw together what should simulate topology B and the results seem...possibly okay?
![image](https://cloud.githubusercontent.com/assets/8922497/19217410/0ab0782c-8d8f-11e6-84d8-091f86fe5a0b.png)

It's a bit odd how C seems to always have priority over A since A supposedly sent less packets, but not sure if that's by design of the protocol. The fact that B sensed collisions while D didn't does make sense though.

**Comment by mackncheesiest** [comment]
Fixed my setup for topology B, and, yeah, I'm not sure if this is too many collisions or not:
![image](https://cloud.githubusercontent.com/assets/8922497/19217582/ccc81e7a-8d93-11e6-825c-ffae3864574f.png)

**Comment by scottmarshall17** [comment]
I'll take a look into the topology and the collision sensing and see if I see anything out of the ordinary regarding what we should expect to be seeing. At first glance, the results seem to show quite a few collisions, but that makes sense if you think about it because the transmitters can't see each other and attempt to send packets the instant they hit the queue. The backoff counters continue to double and the average delay per packet increases quite a bit with the hidden terminal, which also makes some sense. How do the number of packets sent with the hidden terminal approach compare to the standard topology? I'll run the numbers.

**Comment by mackncheesiest** [comment]
So I have a simple two-TX one-RX hidden terminal setup (i.e. A <---> B <---> C) with A and C transmitters and B a receiver, and the test results for it are absolutely terrible. Like, they're managing to get like 5 - 25 packets through at lambda = 50. It almost seems too bad to be real.
![image](https://cloud.githubusercontent.com/assets/8922497/19223758/77cd8e66-8e2c-11e6-862e-74d4af67862f.png)
